### ISSUE TITLE
Project title

### ISSUE THREAD

**Issue by skeptical0ptimist** [nobu-maeda/n3xb#4]
Is it supposed to be 'native nostr' or 'naive nostr'?

**Comment by nobu-maeda** [comment]
Meant to be 'naive'. Because placing clear-text trades in JSON on dumb Nostr relays, that can be worth many Bitcoins is pretty naive? Yet that is the spirit of Nostr, simple inter-operable implementations, and rely on the community and other developers to circle the square. As long as the base protocol is open, extensible, and has no element of for-profit wall gardening, I believe this is possible.
